version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: r1kenpy/kittygram_backend:latest
    env_file: .env
    volumes:
      - static:/static
      - media:/media
    depends_on:
      - db
  frontend:
    env_file: .env
    image: r1kenpy/kittygram_frontend:latest
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static
  gateway:
    image: r1kenpy/kittygram_gateway:latest
    env_file: .env
    volumes:
      - static:/static
      - media:/media
    depends_on:
      - frontend
      - backend
    ports:
      - 9000:80

